# Generated by Django 3.2.10 on 2022-01-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=120, verbose_name='Prenom')),
                ('sexe', models.CharField(max_length=20, verbose_name='Sexe')),
                ('nomp', models.CharField(max_length=120, verbose_name='NomP')),
                ('fonctionp', models.CharField(max_length=120, verbose_name='FonctionP')),
                ('nomm', models.CharField(max_length=120, verbose_name='NomM')),
                ('fonctionm', models.CharField(max_length=120, verbose_name='FonctionM')),
                ('situationM', models.CharField(max_length=120, verbose_name='situation matrimoniale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
